# Generated by Django 5.2 on 2026-03-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='decoration',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Декоративные элементы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_extension_method',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Метод прикрепления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_length',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Длина волос'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_material',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Материал волос'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_shade',
            field=models.CharField(blank=True, choices=[('light', 'Светлый'), ('dark', 'Темный'), ('medium', 'Средний'), ('red', 'Рыжий'), ('combined', 'Смешанный'), ('other', 'Другой')], default='other', max_length=200, verbose_name='Оттенок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Тип волос или канекалона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_width',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ширина волос'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kit',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_strands',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Количество прядей'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='размер упаковки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.5, max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
