# Generated by Django 5.2 on 2026-03-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20260323_1601'),
    ]

    operations = [
    ]
