# Generated by Django 5.2 on 2026-03-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20260323_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='start_price',
        ),
    ]
