# Generated by Django 5.2 on 2026-03-27 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_start_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hair_extension_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hair_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hair_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hair_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hair_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_hit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number_of_strands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='description_override',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_length_override',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_width_override',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_strands_override',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('note_for_manager', models.TextField(blank=True, default='', verbose_name='Примечание для менеджера, чтобы легко находить товары')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('hair_length', models.CharField(blank=True, default='', max_length=200, verbose_name='Длина волос')),
                ('hair_width', models.CharField(blank=True, default='', max_length=200, verbose_name='Ширина волос')),
                ('hair_material', models.CharField(blank=True, default='', max_length=200, verbose_name='Материал волос')),
                ('number_of_strands', models.CharField(blank=True, default='', max_length=200, verbose_name='Количество прядей')),
                ('hair_extension_method', models.CharField(blank=True, default='', max_length=200, verbose_name='Метод прикрепления')),
                ('hair_type', models.CharField(blank=True, default='', max_length=200, verbose_name='Тип волос или канекалона')),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=200, verbose_name='Страна происхождения')),
                ('kit', models.CharField(blank=True, default='', max_length=200, verbose_name='Комплектация')),
                ('decoration', models.CharField(blank=True, default='', max_length=200, verbose_name='Декоративные элементы')),
                ('package', models.CharField(blank=True, default='', max_length=200, verbose_name='Габариты упаковки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ManyToManyField(related_name='series', to='shop.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Серия товаров',
                'verbose_name_plural': 'Серии товаров',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.productseries', verbose_name='Серия'),
        ),
    ]
