# Generated by Django 5.2 on 2026-03-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_override',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание, если отличается от серии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_length_override',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Длина волос, если отличается от серии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_width_override',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Ширина волос, если отличается от серии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_strands_override',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Количество прядей, если отличается от серии'),
        ),
    ]
