# Generated by Django 5.2 on 2026-03-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kit_override',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Комплектация, если отличается от серии'),
        ),
    ]
