# Generated by Django 5.2 on 2026-04-02 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productseries',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='series',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_override',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hair_length_override',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hair_shade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hair_width_override',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kit_override',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number_of_strands_override',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Страна происхождения'),
        ),
        migrations.AddField(
            model_name='product',
            name='decoration',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Декоративные элементы'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='group_slug',
            field=models.SlugField(default='', max_length=255, verbose_name='URL группы'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_extension_method',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Метод прикрепления'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_length',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Длина волос'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_material',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Материал волос'),
        ),
        migrations.AddField(
            model_name='product',
            name='hair_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Тип волос'),
        ),
        migrations.AddField(
            model_name='product',
            name='kit',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Комплектация'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='note_for_manager',
            field=models.TextField(blank=True, default='', verbose_name='Примечание для менеджера'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_strands',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Количество прядей'),
        ),
        migrations.AddField(
            model_name='product',
            name='package',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Материал упаковки'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_dimensions',
            field=models.JSONField(blank=True, help_text="Пример: {'длина': 10, 'ширина': 15, 'высота': 5, 'вес,кг': 0.5}", null=True, verbose_name='Габариты упаковки'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(default='', max_length=200, verbose_name='Группа товаров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(default='', max_length=200, verbose_name='Артикул'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['group_slug'], name='shop_produc_group_s_5cd3c1_idx'),
        ),
        migrations.DeleteModel(
            name='ProductSeries',
        ),
    ]
