# Generated by Django 5.2 on 2026-04-05 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_product_packaging_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(default='', max_length=200, verbose_name='Артикул продавца'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_extension_method',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Способ наращивания волос'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_material',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Вид волос'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.CharField(default='', max_length=200, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Фото'),
        ),
    ]
