# Generated by Django 5.2 on 2026-04-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Популярность'),
        ),
    ]
