# Generated by Django 5.2 on 2026-04-06 07:41

import django.db.models.deletion
import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], max_length=10, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='reviews/%Y/%m/', validators=[shop.validators.validate_review_media], verbose_name='Файл')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='shop.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Медиафайл отзыва',
                'verbose_name_plural': 'Медиафайлы отзывов',
            },
        ),
    ]
