# Generated by Django 5.2 on 2026-04-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_reviewmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViiwsHistory',
        ),
    ]
