# Generated by Django 5.2 on 2026-04-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_hair_width_viiwshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('address', 'Адрес'), ('social', 'Соцсеть / Мессенджер')], default='phone', max_length=20, verbose_name='Тип контакта')),
                ('label', models.CharField(help_text="Напр: 'Отдел продаж' или 'WhatsApp'", max_length=50, verbose_name='Заголовок')),
                ('value', models.CharField(help_text='Сам номер, почта или адрес', max_length=200, verbose_name='Значение')),
                ('url', models.URLField(blank=True, help_text='Для соцсетей или кликабельного номера (tel:+7...)', verbose_name='Ссылка')),
                ('contact_icon', models.ImageField(blank=True, upload_to='contacts/', verbose_name='Иконка')),
                ('svg_icon', models.TextField(blank=True, help_text='Вставьте XML-код иконки <svg>...</svg> без параметров width/height', verbose_name='SVG иконка, если есть)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сорт.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты магазина',
                'ordering': ['sort_order'],
            },
        ),
    ]
