# Generated by Django 5.2 on 2026-04-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_contact_slug_alter_contact_svg_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(help_text='Цифры, латиница, дефисы. БЕЗ пробелов!', unique=True, verbose_name='Слаг'),
        ),
    ]
