# Generated by Django 5.2 on 2026-04-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_contact_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_hit',
        ),
    ]
