# Generated by Django 5.2 on 2026-04-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_info_delete_viiwshistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
    ]
