# Generated by Django 5.2 on 2026-05-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_review_review_answer_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_compressed',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/compressed/', verbose_name='Сжатое фото'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=20),
        ),
    ]
