# Generated by Django 5.2 on 2026-05-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0038_productimage_image_compressed_productimage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="video_compressed",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="products/videos/compressed/",
                verbose_name="Сжатое видео",
            ),
        ),
    ]
