# Generated by Django 5.2 on 2026-05-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0039_productimage_video_compressed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewmedia",
            options={
                "ordering": ["order"],
                "verbose_name": "Медиафайл отзыва",
                "verbose_name_plural": "Медиафайлы отзывов",
            },
        ),
        migrations.AddField(
            model_name="reviewmedia",
            name="file_compressed",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="reviews/compressed/%Y/%m/",
                verbose_name="Сжатый файл",
            ),
        ),
        migrations.AddField(
            model_name="reviewmedia",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewmedia",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("processing", "Обрабатывается"),
                    ("done", "Готово"),
                    ("error", "Ошибка"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
