# Generated by Django 5.2 on 2026-05-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_product_out_of_stock_behavior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_hit',
        ),
    ]
