# Generated by Django 5.2 on 2026-05-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_swap_hair_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hair_shade',
            field=models.CharField(blank=True, choices=[('blond', 'Блонд'), ('light_brown', 'Русый'), ('brown_haired', 'Шатен'), ('black', 'Черный'), ('red', 'Рыжий'), ('mixed', 'Смешанный'), ('not_defined', 'Не определен')], default='not_defined', max_length=200, verbose_name='Оттенок волос'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hair_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина волос'),
        ),
    ]
