# Generated by Django 5.2 on 2026-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_remove_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hair_shade',
            field=models.CharField(blank=True, choices=[('blond', 'Блонд'), ('dark_brown', 'Темно-русый'), ('medium_brown', 'Средне-русый'), ('light_brown', 'Светло-русый'), ('brown_haired', 'Шатен'), ('black', 'Черный'), ('red', 'Рыжий'), ('mixed', 'Смешанный'), ('not_defined', 'Не определен')], default='not_defined', max_length=200, verbose_name='Оттенок волос'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.CharField(default='_', max_length=200, verbose_name='Группа'),
        ),
    ]
