# Generated by Django 5.2 on 2026-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0051_alter_product_hair_shade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="hair_shade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blond", "Блонд"),
                    ("ash", "Пепельный"),
                    ("medium_brown", "Русый"),
                    ("brown_haired", "Каштан"),
                    ("black", "Черный"),
                    ("ginger", "Рыжий"),
                    ("red", "Красный"),
                    ("highlighting", "Мелирование"),
                    ("ombre", "Омбре"),
                    ("mixed_color", "цветные"),
                    ("not_defined", "Не определен"),
                ],
                default="not_defined",
                max_length=200,
                verbose_name="Оттенок волос",
            ),
        ),
    ]
