# Generated by Django 5.2 on 2026-05-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0052_alter_product_hair_shade"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="В архиве"),
        ),
    ]
