# Generated by Django 5.2 on 2026-05-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0053_order_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата доставки"
            ),
        ),
    ]
