# Generated by Django 5.2 on 2026-05-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_product_variants_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants_reviewed',
        ),
    ]
