# Generated by Django 5.2 on 2026-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_producthairshade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants_reviewed',
            field=models.BooleanField(default=False, verbose_name='Варианты проверены'),
        ),
    ]
