# Generated by Django 5.2 on 2026-05-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_product_variants_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hair_shade',
        ),
    ]
