# Generated by Django 5.2 on 2026-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0061_add_pg_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_manager_note",
            field=models.TextField(blank=True, verbose_name="Примечание менеджера"),
        ),
    ]
