# Generated by Django 5.2 on 2026-06-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0062_order_assigned_manager_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="advantages",
            field=models.TextField(blank=True, null=True, verbose_name="Достоинства"),
        ),
        migrations.AddField(
            model_name="review",
            name="disadvantages",
            field=models.TextField(blank=True, null=True, verbose_name="Недостатки"),
        ),
    ]
