# Generated by Django 5.2 on 2026-06-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0063_review_advantages_review_disadvantages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(default="", verbose_name="Текст отзыва"),
        ),
    ]
