# Generated by Django 5.2 on 2026-06-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0064_alter_review_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Имя автора"
            ),
        ),
    ]
