# Generated by Django 5.2 on 2026-06-23 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0065_review_author_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("product", "user", "author_name")},
        ),
    ]
