# Generated by Django 5.2 on 2026-06-23 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0066_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
