# Generated by Django 5.2 on 2026-06-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0068_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="author_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Имя автора"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, default="", verbose_name="Текст отзыва"),
        ),
    ]
