# Generated by Django 5.2 on 2026-09-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_alter_review_author_name_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость доставки')),
                ('free_delivery_threshold', models.PositiveIntegerField(default=0, help_text='0 — без бесплатной доставки', verbose_name='Бесплатная доставка от')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название региона')),
                ('region_code', models.CharField(blank=True, help_text="Например, '54' для Новосибирской области", max_length=10, null=True, verbose_name='Код региона')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='shop.deliveryzone')),
            ],
        ),
    ]
