# Generated by Django 5.2 on 2026-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_deliveryzone_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'verbose_name': 'Зона доставки', 'verbose_name_plural': 'Зоны доставки'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='group_slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='НЕ РЕДАКТИРОВАТЬ!!!'),
        ),
    ]
