# Generated by Django 5.2 on 2026-05-13 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushsubscription",
            options={
                "verbose_name": "Подписка на уведомления",
                "verbose_name_plural": "Подписки на уведомления",
            },
        ),
    ]
