# Generated by Django 5.2 on 2026-03-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_set_username_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_postal_code',
            field=models.CharField(default='', max_length=20, verbose_name='индекс'),
        ),
    ]
